config/routes.rb
Rails.application.routes.draw do

  root "departments#index"

  resources :departments do
    resources :items
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/department.rb
class Department < ApplicationRecord
  has_many :items
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :department
  validates :price, numericality: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/departments_controller.rb
class DepartmentsController < ApplicationController
  before_action :set_department, only: [:show, :edit, :update, :destroy]

  def index
    @departments = Department.all
  end

  def show

  end

  def new
    @department = Department.new
    render partial: "form"
  end

  def create
    @department = Department.new(department_params)

    if @department.save
      redirect_to departments_path
    else
      render :new
    end
  end

  def edit
    render partial: "form"
  end

  def update
    if @department.update(department_params)
      redirect_to department_path
    else
      render :edit
    end
  end

  def destroy
    @department.destroy
    redirect_to departments_path
  end



private
  def department_params
    params.require(:department).permit(:name)
  end

  def set_department
    @department = Department.find(params[:id])
  end


end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_department
  before_action :set_item, only: [:show, :edit, :update, :destroy]
  
  def edit
    render partial: "form"
  end

  def update
    if @item.update(item_params)
      redirect_to [@department, @item]
    else
      render :edit
    end
  end

  def index
    @items = @department.items
  end

  def show

  end

  def new
    @item = @department.items.new
    render partial: "form"
  end

  def create
    @item = @department.items.new(item_params)

    if @department.save
      redirect_to department_items_path(@department)
    else
      render :new
    end
  end

  def destroy
    @item.destroy
    redirect_to department_items_path(@department)
  end

  private
    def set_department
      @department = Department.find(params[:department_id])
    end

    def set_item
      @item = Item.find(params[:id])
    end

    def item_params
      params.require(:item).permit(:name, :price, :description)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/departments_helper.rb
module DepartmentsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/departments/_form.html.erb
<h1><%= @department.id ? "Edit Department" : "New Department" %>
<hr />
<%= form_for @department do |f| %>
<%= f.label :name %>
<%= f.text_field :name, required: true, autofocus: true %>

<%= f.submit %>
<% end %>

app/views/departments/edit.html.erb
<h1>Departments#edit</h1>
<p>Find me in app/views/departments/edit.html.erb</p>

app/views/departments/index.html.erb
<h1> Click a Department to view content </h2>
<%= link_to "Create a new Department", new_department_path %>

<h3><%= @departments.length === 0 ? "No Departments Added" : ""%></h3>
<ul>
  <% @departments.each do |department|%>
    <li><%= link_to department.name, department_path(department) %></li>
  <% end %>
</ul>

app/views/departments/new.html.erb
<h1>Departments#new</h1>
<p>Find me in app/views/departments/new.html.erb</p>

app/views/departments/show.html.erb
<h1><%= @department.name %></h1>
<hr />
<p>What would you like to do?</p>

<%= link_to "View Items", department_items_path(@department) %>
<br />
<%= link_to "Edit Department", edit_department_path(@department) %>
<br />
<%= link_to "Delete Department", department_path(@department), method: :delete %>
<br />
<%= link_to 'Back to Departments', departments_path %>

app/views/items/_form.html.erb
<h1><%= @item.id ? 'Edit Item' : 'Create Item' %></h1>
<hr />
<h2><%= @department.name %></h2>
<br />
<%= form_for [@department, @item] do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, required: true, autofocus: true %>
  <br />
  <%= f.label :price %>
  <%= f.text_field :price, required: true %>
  <br />
  <%= f.label :description %>
  <%= f.text_area :description, required: true %>
  <%= f.submit%>
<% end %>
<%= link_to 'Back to Department', department_path(@department) %>

app/views/items/edit.html.erb
<h1>Items#edit</h1>
<p>Find me in app/views/items/edit.html.erb</p>

app/views/items/index.html.erb
<h1>Click an Item to View its details</h1>
<%= link_to 'Create a new Item', new_department_item_path(@department) %>
<br />
<%= link_to 'Back to Department', department_path(@department) %>
<ul>
  <% @items.each do |item| %>
    <h3><%= @department.name%></h3>
    <li><%= link_to item.name, [@department, item] %></li>
  <% end %>
</ul>

app/views/items/new.html.erb
<h1>Items#new</h1>
<p>Find me in app/views/items/new.html.erb</p>

app/views/items/show.html.erb
<h1><%= @department.name %> - <%= @item.name %></h1>
<p>$<%= @item.price %></p>
<p><%= @item.description %></p>
<%= link_to 'Edit Item', edit_department_item_path([@department, @item])%>
<%= link_to 'Delete Item', [@department, @item], method: :delete %>
<%= link_to 'Back to Items', department_items_path(@department) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Dpstore</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>